import NextAuthProvider from '@/Providers/NextAuthProvider';
import SessionProviderWrapper from '@/Providers/SessionProvider';
import { ThemeProvider } from '@/Providers/ThemeProvider';
import Footer from './components/Footer';
import Navbar from './components/Navbar';
import './globals.css';

export const metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default async function RootLayout({ children }) {
    const session = await getServerSession(authOptions);
    const safeSession = session
        ? {
              ...session,
              user: {
                  ...session.user,
                  id: session?.user?.id ? session.user.id.toString() : null,
              },
          }
        : null;
    return (
        <html lang="en" suppressHydrationWarning>
            <body
                className={`${geistSans.variable} ${geistMono.variable} antialiased`}
            >
                <SessionProviderWrapper session={safeSession}>
                    <ThemeProvider
                        attribute="class"
                        defaultTheme="system"
                        enableSystem
                        disableTransitionOnChange
                    >
                        <Navbar />
                        <NextAuthProvider>{children}</NextAuthProvider>
                        <Footer />
                    </ThemeProvider>
                </SessionProviderWrapper>
            </body>
        </html>
    );
}
